### PR TITLE
search function implemented.

### PR DESCRIPTION
**Pull request by strobba**
I felt a need for a method to search scb data from python, hence I implemented a search function. However, there is a request limit at scb which forced me to slow down the search. So by now its kind of slow. I raised an issue, with a potential solution to this. For now, the search can be slow imo.

### CODE REVIEW

**Review by docNord — COMMENTED** [review]
Nice work!
The docstring is no longer correct as the function is no longer slow with the stored index, should be updated.
( there are tests which haven't been fulfilled yet)

**Comment by strobba** [comment]
> Nice work! The docstring is no longer correct as the function is no longer slow with the stored index, should be updated. ( there are tests which haven't been fulfilled yet)

Doc string removed. I'll fix linting. However, @mgcth why didn't my local ruff catch these things? Edit: Aha, ruff has no type checker. It is mypy who check the types...

**Comment by strobba** [comment]
@mgcth considering the gist badge that fails in the test, where do I find it and how do i correct it?

**Comment by docNord** [comment]
> @mgcth considering the gist badge that fails in the test, where do I find it and how do i correct it?

@mgcth I am interested in this answer too :)

**Comment by mgcth** [comment]
You find it here https://github.com/Ingenjorsarbete-For-Klimatet/ifk-scb-compilations/pull/4 and needed to rebase/merge main into here.

**Comment by docNord** [comment]
Ah, so it was the same issue again. Thanks @mgcth 🙌😊

**Pull request merged**
